config/routes.rb
Rails.application.routes.draw do
 root 'tasks#index'

  get 'tasks/active'

  get 'tasks/complete'

  post 'tasks/:id/complete' => 'tasks#complete'

  post 'tasks/:id/uncomplete' => 'tasks#uncomplete'

  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def uncomplete
    @task = Task.find(params[:id])
    @task.checked = false
    @task.save
    redirect_to tasks_path
  end

  def complete
    @task = Task.find(params[:id])
    @task.checked = true
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to tasks_path
    else
      render 'edit'
    end
  end

  def create
    p "*"*50
    p task_params
    p "*"*50

    @task = Task.new(params.require(:task).permit(:name))

    @task.save
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:name,:checked)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for :task, url: task_path(@task), method: :patch do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/tasks/active.html.erb
<h1>Tasks#active</h1>
<p>Find me in app/views/tasks/active.html.erb</p>

app/views/tasks/complete.html.erb
<h1>Tasks#complete</h1>
<p>Find me in app/views/tasks/complete.html.erb</p>

app/views/tasks/edit.html.erb
<%#= render 'tasks/form' %>
<%= form_for :task, url: task_path(@task), method: :patch do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/tasks/index.html.erb
<h1>Todos</h1>
<%= form_for :task, url: tasks_path do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

<% @tasks.each do |task| %>
  <p style="font-size: 1.5em">  <%= task.name %> <%= link_to("Edit",edit_task_path(task)) %> <%= link_to("Delete",task_path(task), method: :delete) %>
    <% if task.checked %>
      <%= button_to "Uncomplete", {id: task.id, action: 'uncomplete'} %>
    <% else %>
      <%= button_to "Complete", {id: task.id, action: 'complete'}  %>
    <% end %>

  </p>
<% end %>